---
- name: This is a recipe for how to run packit tests
  hosts: all
  tasks:
  - include_tasks: tasks/zuul-project-setup.yaml
  - include_tasks: tasks/generic-dnf-requirements.yaml
  - include_tasks: tasks/rpm-test-deps.yaml
  - include_tasks: tasks/checkout_ogr.yaml

  - name: Run tests
    command: pytest-3 -v tests
    args:
      chdir: '{{ reverse_dir }}'
    environment:
      PYTHONPATH: '{{ project_dir }}'
